/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SIslamHead, } from "./components/s-islam-header/interface/common.inreface";
export namespace Components {
    interface MyComponent {
    }
    interface SIslamComment {
        "forComment": any;
    }
    interface SIslamEvents {
        "forUpcoming": any;
    }
    interface SIslamExplore {
        "forExplore": any;
    }
    interface SIslamFooter {
        "forFooter": any;
    }
    interface SIslamHeader {
        "forHeader": any;
        /**
          * Приём данных из массива для вывода
         */
        "intro": SIslamHead[];
    }
    interface SIslamHome {
    }
    interface SIslamItemBlog {
        "database": any;
    }
    interface SIslamItemComment {
        "forComment": any;
    }
    interface SIslamItemExplore {
        "forExplore": any;
    }
    interface SIslamItemMailbox {
        "forMailBox": any;
    }
    interface SIslamItemPop {
        "forPopular": any;
    }
    interface SIslamItemPostA {
        "post": any;
    }
    interface SIslamItemSubscribe {
        "forSubscribe": any;
    }
    interface SIslamMailbox {
        "forMailBox": any;
    }
    interface SIslamNewBlog {
        "database": any;
    }
    interface SIslamNewPostA {
        "forPost": any;
        "items": any;
    }
    interface SIslamNews {
        "forThird": any;
    }
    interface SIslamPopular {
        "forPopular": any;
    }
    interface SIslamSidebarA {
        "sidebar": any;
    }
    interface SIslamSubscribe {
        "forSubscribe": any;
    }
    interface SIslamThird {
        "forThird": any;
    }
    interface SIslamUpcoming {
        "forUpcoming": any;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSIslamCommentElement extends Components.SIslamComment, HTMLStencilElement {
    }
    var HTMLSIslamCommentElement: {
        prototype: HTMLSIslamCommentElement;
        new (): HTMLSIslamCommentElement;
    };
    interface HTMLSIslamEventsElement extends Components.SIslamEvents, HTMLStencilElement {
    }
    var HTMLSIslamEventsElement: {
        prototype: HTMLSIslamEventsElement;
        new (): HTMLSIslamEventsElement;
    };
    interface HTMLSIslamExploreElement extends Components.SIslamExplore, HTMLStencilElement {
    }
    var HTMLSIslamExploreElement: {
        prototype: HTMLSIslamExploreElement;
        new (): HTMLSIslamExploreElement;
    };
    interface HTMLSIslamFooterElement extends Components.SIslamFooter, HTMLStencilElement {
    }
    var HTMLSIslamFooterElement: {
        prototype: HTMLSIslamFooterElement;
        new (): HTMLSIslamFooterElement;
    };
    interface HTMLSIslamHeaderElement extends Components.SIslamHeader, HTMLStencilElement {
    }
    var HTMLSIslamHeaderElement: {
        prototype: HTMLSIslamHeaderElement;
        new (): HTMLSIslamHeaderElement;
    };
    interface HTMLSIslamHomeElement extends Components.SIslamHome, HTMLStencilElement {
    }
    var HTMLSIslamHomeElement: {
        prototype: HTMLSIslamHomeElement;
        new (): HTMLSIslamHomeElement;
    };
    interface HTMLSIslamItemBlogElement extends Components.SIslamItemBlog, HTMLStencilElement {
    }
    var HTMLSIslamItemBlogElement: {
        prototype: HTMLSIslamItemBlogElement;
        new (): HTMLSIslamItemBlogElement;
    };
    interface HTMLSIslamItemCommentElement extends Components.SIslamItemComment, HTMLStencilElement {
    }
    var HTMLSIslamItemCommentElement: {
        prototype: HTMLSIslamItemCommentElement;
        new (): HTMLSIslamItemCommentElement;
    };
    interface HTMLSIslamItemExploreElement extends Components.SIslamItemExplore, HTMLStencilElement {
    }
    var HTMLSIslamItemExploreElement: {
        prototype: HTMLSIslamItemExploreElement;
        new (): HTMLSIslamItemExploreElement;
    };
    interface HTMLSIslamItemMailboxElement extends Components.SIslamItemMailbox, HTMLStencilElement {
    }
    var HTMLSIslamItemMailboxElement: {
        prototype: HTMLSIslamItemMailboxElement;
        new (): HTMLSIslamItemMailboxElement;
    };
    interface HTMLSIslamItemPopElement extends Components.SIslamItemPop, HTMLStencilElement {
    }
    var HTMLSIslamItemPopElement: {
        prototype: HTMLSIslamItemPopElement;
        new (): HTMLSIslamItemPopElement;
    };
    interface HTMLSIslamItemPostAElement extends Components.SIslamItemPostA, HTMLStencilElement {
    }
    var HTMLSIslamItemPostAElement: {
        prototype: HTMLSIslamItemPostAElement;
        new (): HTMLSIslamItemPostAElement;
    };
    interface HTMLSIslamItemSubscribeElement extends Components.SIslamItemSubscribe, HTMLStencilElement {
    }
    var HTMLSIslamItemSubscribeElement: {
        prototype: HTMLSIslamItemSubscribeElement;
        new (): HTMLSIslamItemSubscribeElement;
    };
    interface HTMLSIslamMailboxElement extends Components.SIslamMailbox, HTMLStencilElement {
    }
    var HTMLSIslamMailboxElement: {
        prototype: HTMLSIslamMailboxElement;
        new (): HTMLSIslamMailboxElement;
    };
    interface HTMLSIslamNewBlogElement extends Components.SIslamNewBlog, HTMLStencilElement {
    }
    var HTMLSIslamNewBlogElement: {
        prototype: HTMLSIslamNewBlogElement;
        new (): HTMLSIslamNewBlogElement;
    };
    interface HTMLSIslamNewPostAElement extends Components.SIslamNewPostA, HTMLStencilElement {
    }
    var HTMLSIslamNewPostAElement: {
        prototype: HTMLSIslamNewPostAElement;
        new (): HTMLSIslamNewPostAElement;
    };
    interface HTMLSIslamNewsElement extends Components.SIslamNews, HTMLStencilElement {
    }
    var HTMLSIslamNewsElement: {
        prototype: HTMLSIslamNewsElement;
        new (): HTMLSIslamNewsElement;
    };
    interface HTMLSIslamPopularElement extends Components.SIslamPopular, HTMLStencilElement {
    }
    var HTMLSIslamPopularElement: {
        prototype: HTMLSIslamPopularElement;
        new (): HTMLSIslamPopularElement;
    };
    interface HTMLSIslamSidebarAElement extends Components.SIslamSidebarA, HTMLStencilElement {
    }
    var HTMLSIslamSidebarAElement: {
        prototype: HTMLSIslamSidebarAElement;
        new (): HTMLSIslamSidebarAElement;
    };
    interface HTMLSIslamSubscribeElement extends Components.SIslamSubscribe, HTMLStencilElement {
    }
    var HTMLSIslamSubscribeElement: {
        prototype: HTMLSIslamSubscribeElement;
        new (): HTMLSIslamSubscribeElement;
    };
    interface HTMLSIslamThirdElement extends Components.SIslamThird, HTMLStencilElement {
    }
    var HTMLSIslamThirdElement: {
        prototype: HTMLSIslamThirdElement;
        new (): HTMLSIslamThirdElement;
    };
    interface HTMLSIslamUpcomingElement extends Components.SIslamUpcoming, HTMLStencilElement {
    }
    var HTMLSIslamUpcomingElement: {
        prototype: HTMLSIslamUpcomingElement;
        new (): HTMLSIslamUpcomingElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "s-islam-comment": HTMLSIslamCommentElement;
        "s-islam-events": HTMLSIslamEventsElement;
        "s-islam-explore": HTMLSIslamExploreElement;
        "s-islam-footer": HTMLSIslamFooterElement;
        "s-islam-header": HTMLSIslamHeaderElement;
        "s-islam-home": HTMLSIslamHomeElement;
        "s-islam-item-blog": HTMLSIslamItemBlogElement;
        "s-islam-item-comment": HTMLSIslamItemCommentElement;
        "s-islam-item-explore": HTMLSIslamItemExploreElement;
        "s-islam-item-mailbox": HTMLSIslamItemMailboxElement;
        "s-islam-item-pop": HTMLSIslamItemPopElement;
        "s-islam-item-post-a": HTMLSIslamItemPostAElement;
        "s-islam-item-subscribe": HTMLSIslamItemSubscribeElement;
        "s-islam-mailbox": HTMLSIslamMailboxElement;
        "s-islam-new-blog": HTMLSIslamNewBlogElement;
        "s-islam-new-post-a": HTMLSIslamNewPostAElement;
        "s-islam-news": HTMLSIslamNewsElement;
        "s-islam-popular": HTMLSIslamPopularElement;
        "s-islam-sidebar-a": HTMLSIslamSidebarAElement;
        "s-islam-subscribe": HTMLSIslamSubscribeElement;
        "s-islam-third": HTMLSIslamThirdElement;
        "s-islam-upcoming": HTMLSIslamUpcomingElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface SIslamComment {
        "forComment"?: any;
    }
    interface SIslamEvents {
        "forUpcoming"?: any;
    }
    interface SIslamExplore {
        "forExplore"?: any;
    }
    interface SIslamFooter {
        "forFooter"?: any;
    }
    interface SIslamHeader {
        "forHeader"?: any;
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: SIslamHead[];
        /**
          * Клик по Articles
         */
        "onClickHeaderArticles"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Button
         */
        "onClickHeaderButton"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Customer Stories
         */
        "onClickHeaderCustomerStories"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Events
         */
        "onClickHeaderEvents"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Icon
         */
        "onClickHeaderIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Input
         */
        "onClickHeaderInput"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Reports
         */
        "onClickHeaderReports"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по картинке
         */
        "onClickHeaderUrl"?: (event: CustomEvent<any>) => void;
    }
    interface SIslamHome {
    }
    interface SIslamItemBlog {
        "database"?: any;
    }
    interface SIslamItemComment {
        "forComment"?: any;
    }
    interface SIslamItemExplore {
        "forExplore"?: any;
    }
    interface SIslamItemMailbox {
        "forMailBox"?: any;
    }
    interface SIslamItemPop {
        "forPopular"?: any;
    }
    interface SIslamItemPostA {
        "post"?: any;
    }
    interface SIslamItemSubscribe {
        "forSubscribe"?: any;
    }
    interface SIslamMailbox {
        "forMailBox"?: any;
    }
    interface SIslamNewBlog {
        "database"?: any;
    }
    interface SIslamNewPostA {
        "forPost"?: any;
        "items"?: any;
    }
    interface SIslamNews {
        "forThird"?: any;
    }
    interface SIslamPopular {
        "forPopular"?: any;
    }
    interface SIslamSidebarA {
        "sidebar"?: any;
    }
    interface SIslamSubscribe {
        "forSubscribe"?: any;
    }
    interface SIslamThird {
        "forThird"?: any;
    }
    interface SIslamUpcoming {
        "forUpcoming"?: any;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "s-islam-comment": SIslamComment;
        "s-islam-events": SIslamEvents;
        "s-islam-explore": SIslamExplore;
        "s-islam-footer": SIslamFooter;
        "s-islam-header": SIslamHeader;
        "s-islam-home": SIslamHome;
        "s-islam-item-blog": SIslamItemBlog;
        "s-islam-item-comment": SIslamItemComment;
        "s-islam-item-explore": SIslamItemExplore;
        "s-islam-item-mailbox": SIslamItemMailbox;
        "s-islam-item-pop": SIslamItemPop;
        "s-islam-item-post-a": SIslamItemPostA;
        "s-islam-item-subscribe": SIslamItemSubscribe;
        "s-islam-mailbox": SIslamMailbox;
        "s-islam-new-blog": SIslamNewBlog;
        "s-islam-new-post-a": SIslamNewPostA;
        "s-islam-news": SIslamNews;
        "s-islam-popular": SIslamPopular;
        "s-islam-sidebar-a": SIslamSidebarA;
        "s-islam-subscribe": SIslamSubscribe;
        "s-islam-third": SIslamThird;
        "s-islam-upcoming": SIslamUpcoming;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "s-islam-comment": LocalJSX.SIslamComment & JSXBase.HTMLAttributes<HTMLSIslamCommentElement>;
            "s-islam-events": LocalJSX.SIslamEvents & JSXBase.HTMLAttributes<HTMLSIslamEventsElement>;
            "s-islam-explore": LocalJSX.SIslamExplore & JSXBase.HTMLAttributes<HTMLSIslamExploreElement>;
            "s-islam-footer": LocalJSX.SIslamFooter & JSXBase.HTMLAttributes<HTMLSIslamFooterElement>;
            "s-islam-header": LocalJSX.SIslamHeader & JSXBase.HTMLAttributes<HTMLSIslamHeaderElement>;
            "s-islam-home": LocalJSX.SIslamHome & JSXBase.HTMLAttributes<HTMLSIslamHomeElement>;
            "s-islam-item-blog": LocalJSX.SIslamItemBlog & JSXBase.HTMLAttributes<HTMLSIslamItemBlogElement>;
            "s-islam-item-comment": LocalJSX.SIslamItemComment & JSXBase.HTMLAttributes<HTMLSIslamItemCommentElement>;
            "s-islam-item-explore": LocalJSX.SIslamItemExplore & JSXBase.HTMLAttributes<HTMLSIslamItemExploreElement>;
            "s-islam-item-mailbox": LocalJSX.SIslamItemMailbox & JSXBase.HTMLAttributes<HTMLSIslamItemMailboxElement>;
            "s-islam-item-pop": LocalJSX.SIslamItemPop & JSXBase.HTMLAttributes<HTMLSIslamItemPopElement>;
            "s-islam-item-post-a": LocalJSX.SIslamItemPostA & JSXBase.HTMLAttributes<HTMLSIslamItemPostAElement>;
            "s-islam-item-subscribe": LocalJSX.SIslamItemSubscribe & JSXBase.HTMLAttributes<HTMLSIslamItemSubscribeElement>;
            "s-islam-mailbox": LocalJSX.SIslamMailbox & JSXBase.HTMLAttributes<HTMLSIslamMailboxElement>;
            "s-islam-new-blog": LocalJSX.SIslamNewBlog & JSXBase.HTMLAttributes<HTMLSIslamNewBlogElement>;
            "s-islam-new-post-a": LocalJSX.SIslamNewPostA & JSXBase.HTMLAttributes<HTMLSIslamNewPostAElement>;
            "s-islam-news": LocalJSX.SIslamNews & JSXBase.HTMLAttributes<HTMLSIslamNewsElement>;
            "s-islam-popular": LocalJSX.SIslamPopular & JSXBase.HTMLAttributes<HTMLSIslamPopularElement>;
            "s-islam-sidebar-a": LocalJSX.SIslamSidebarA & JSXBase.HTMLAttributes<HTMLSIslamSidebarAElement>;
            "s-islam-subscribe": LocalJSX.SIslamSubscribe & JSXBase.HTMLAttributes<HTMLSIslamSubscribeElement>;
            "s-islam-third": LocalJSX.SIslamThird & JSXBase.HTMLAttributes<HTMLSIslamThirdElement>;
            "s-islam-upcoming": LocalJSX.SIslamUpcoming & JSXBase.HTMLAttributes<HTMLSIslamUpcomingElement>;
        }
    }
}
